### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zwb124** [pxia/mpv-macos-build#1]
What should I do if I keep making this mistake?

“gnutls not found using pkg-config”

**Comment by zwb124** [comment]
Could you send me a copy of your compiled app? Thank you

**Comment by pxia** [comment]
can you try adding `gnutls` at the end of line 11 of `build.sh`?

**Comment by zwb124** [comment]
> can you try adding `gnutls` at the end of line 11 of `build.sh`?

I added, but still prompted the same error

**Comment by zwb124** [comment]
Warning: jpeg 9e is already installed and up-to-date.
To reinstall 9e, run:
  brew reinstall jpeg
Warning: libarchive 3.6.1 is already installed and up-to-date.
To reinstall 3.6.1, run:
  brew reinstall libarchive
Warning: libass 0.15.2 is already installed and up-to-date.
To reinstall 0.15.2, run:
  brew reinstall libass
Warning: little-cms2 2.13.1 is already installed and up-to-date.
To reinstall 2.13.1, run:
  brew reinstall little-cms2
Warning: luajit-openresty 2.1-20220411 is already installed and up-to-date.
To reinstall 2.1-20220411, run:
  brew reinstall luajit-openresty
Warning: mujs 1.2.0 is already installed and up-to-date.
To reinstall 1.2.0, run:
  brew reinstall mujs
Warning: uchardet 0.0.7 is already installed and up-to-date.
To reinstall 0.0.7, run:
  brew reinstall uchardet
Warning: vapoursynth 58 is already installed and up-to-date.
To reinstall 58, run:
  brew reinstall vapoursynth
Warning: yt-dlp 2022.5.18 is already installed and up-to-date.
To reinstall 2022.5.18, run:
  brew reinstall yt-dlp
Warning: gnutls 3.7.4 is already installed and up-to-date.
To reinstall 3.7.4, run:
  brew reinstall gnutls
ERROR: gnutls not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by pxia** [comment]
Can you try the latest commit?

**Comment by zwb124** [comment]
> Can you try the latest commit?

The result is the same

**Comment by zwb124** [comment]
You have compiled mpv.app? Can you copy it to me？

**Comment by pxia** [comment]
I added a release.
